import Head from 'next/head'
import styles from '../styles/Home.module.css';
import BlockchainUtils from '../utils/blockchainUtils';
import AztecComponent from '../components/AztecComponent';
import SwapComponent from '../components/SwapComponent';
import { useState, useEffect } from 'react';
import Web3 from 'web3';


export default function Home() {

  const [aztecComponent, setAztecComponent] = useState(true);
  const [connectedAccount, setConnectedAccount] = useState('');

  useEffect(async () => {
    BlockchainUtils.metamaskRefresh();
    let accounts;
    const web3 = BlockchainUtils.getWeb3();
    accounts = await BlockchainUtils.getAccounts(web3)
    const network = await BlockchainUtils.getNetworkType(web3);
    if (accounts.length === 0) {
      Web3.givenProvider.enable();
    } else {
      setConnectedAccount(accounts[0])
      if (network !== 'goerli') {
        alert('Please switch to goerli testnet network.')
      }
    }
  }), [connectedAccount];

  const switchPage = () => {
    setAztecComponent(current => !current)
  }

  return (

    <div className={styles.container} >
      <Head>
        <title>Incrediswap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div>
          <p className={styles.title}>Welcome to the Aztec rollup swap on Uniswap v3</p>
        </div>
      </header>
      <main className={styles.main}>
        <div className={styles.card}>
          {aztecComponent ? <AztecComponent account={connectedAccount} /> : <SwapComponent />}
        </div>

        <button onClick={switchPage} className={styles.button}>Go to {aztecComponent ? "Swap page" : "Aztec Component"}</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/IncrediSwap"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by{' '}
          <span className={styles.logo}>
            IncrediSwap team
          </span>
        </a>
      </footer>
    </div>
  )
}
