import Head from 'next/head'
import styles from '../styles/Home.module.css';
import BlockchainUtils from '../utils/blockchainUtils';
import AztecComponent from '../components/AztecComponent';
import SwapComponent from '../components/SwapComponent';
import { useState, useEffect } from 'react';
import Web3 from 'web3';


export default function Home() {

  const [aztecComponent, setAztecComponent] = useState(true);

  useEffect(async () => {
    BlockchainUtils.metamaskRefresh();
    let accounts;
    const web3 = BlockchainUtils.getWeb3();
    accounts = await BlockchainUtils.getAccounts(web3)
    const network = await BlockchainUtils.getNetworkType(web3);
    if (accounts.length === 0) {
      Web3.givenProvider.enable();
    }
    if (network !== 'goerli') {
      alert('Please switch to goerli testnet network.')
    }
  });

  const switchPage = () => {
    setAztecComponent(current => !current)
  }

  return (

    <div className={styles.container} >
      <Head>
        <title>Incrediswap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {aztecComponent ? <AztecComponent /> : <SwapComponent />}
        <button onClick={switchPage} className={styles.button}>Go to {aztecComponent ? "Swap page" : "Aztec Component"}</button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/IncrediSwap"
          target="_blank"
          rel="noopener noreferrer"
        >
          Developed by{' '}
          <span className={styles.logo}>
            IncrediSwap team
          </span>
        </a>
      </footer>
    </div>
  )
}
